name: Branch Perf Test
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v2
      with:
       node-version: '14'
    - name: Install dependencies
      run: npm ci
    - name: Install k6
      run: |
        curl https://github.com/grafana/k6/releases/download/v0.40.0/k6-v0.40.0-linux-amd64.tar.gz -L | tar xvz --strip-components 1
    - name: Run K6 scripts 
      run: ./k6 run -e MY_HOSTNAME=reqres.in/api/users demo.js